### PR TITLE
fix: framer-motion peer dependency error

### PR DESCRIPTION
**Pull request by rijk**
This should hopefully fix all these errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: scroller-motion@1.2.0
npm ERR! Found: framer-motion@7.6.1
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"^7.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer framer-motion@"^6.5.0" from scroller-motion@1.2.0
npm ERR! node_modules/scroller-motion
npm ERR!   scroller-motion@"^1.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: framer-motion@6.5.1
npm ERR! node_modules/framer-motion
npm ERR!   peer framer-motion@"^6.5.0" from scroller-motion@1.2.0
npm ERR!   node_modules/scroller-motion
npm ERR!     scroller-motion@"^1.2.0" from the root project
```

### CODE REVIEW

**Review by rijk — COMMENTED** [review]
_[moved to description]_

**Comment by rijk** [comment]
BTW, I tested with `framer-motion@7.6.1` and everything is working fine at first glance.

**Review by breadadams — APPROVED** [review]
Thanks a lot for this @rijk 💯

**Comment by breadadams** [comment]
This has been released in [`v1.2.1`](https://github.com/breadadams/scroller-motion/releases/tag/v1.2.1) 🎉

**Comment by sahandii** [comment]
Hi, i get this error. Can you help me? Thx

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: polyroom-app-landing-2023@0.1.0
npm ERR! Found: framer-motion@8.0.2
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"^8.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer framer-motion@"^6.5.0 || ^7.0" from scroller-motion@1.2.1
npm ERR! node_modules/scroller-motion
npm ERR!   scroller-motion@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by breadadams** [comment]
Hey @sahandii, I'll release a fix in the next 12 hours. Will report back here once it's ready.

**Comment by breadadams** [comment]
@sahandii, this should be resolved in [`v1.2.2`](https://github.com/breadadams/scroller-motion/releases/tag/v1.2.2).

**Pull request merged**
